#!/usr/bin/env bash
# Build the Claude Code settings file for an implement run, from config.yml.
#
# The Write/Edit deny rules used to be typed into settings/implement.json by
# hand, next to a comment telling you to remember to update them whenever
# gate.deny changed. That worked in the repository it was written for and
# nowhere else: a new project had to translate its own denylist into forty lines
# of JSON before the harness would even pass its own checks.
#
# So they are derived. gate.deny is the one list; every entry in it becomes a
# Write() and an Edit() deny here. The two cannot disagree because there are no
# longer two of them.
#
# What stays hand-written in settings/implement.json: the rules that are about
# the HARNESS rather than the project -- no `git push`, no `gh`, no `curl` --
# plus the always-safe allow list. Those are the same for everyone.
#
# Usage: avengers-12/lib/emit-settings.sh [output-path]
# Default output: .loop/settings-implement.json

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=avengers-12/lib/common.sh
source "$HERE/common.sh"

require_cmd jq python3
avengers_load_config

BASE="$(cfg paths.settings "avengers-12/settings")/implement.json"
OUT="${1:-$LOOP_DIR/settings-implement.json}"

[[ -s "$BASE" ]] || die "no base settings at $BASE"

mkdir -p "$(dirname "$OUT")"

# jq does the whole merge, so there is one place where the shape of the file is
# decided. `unique` keeps it stable: a duplicated deny is harmless but makes two
# runs produce byte-different files, which makes drift impossible to spot.
jq -n \
  --slurpfile base "$BASE" \
  --slurpfile cfg "$_AVENGERS_CONFIG_JSON" \
  '
  ($base[0]) as $b
  | ($cfg[0]) as $c
  | ($c.gate.deny // [])            as $deny
  | ($c.permissions.denyRead // []) as $denyRead
  | ($c.permissions.allowBash // []) as $allowBash
  | $b
  | .permissions.deny = (
      ($b.permissions.deny // [])
      + ($deny     | map("Write(" + . + ")", "Edit(" + . + ")"))
      + ($denyRead | map("Read(" + . + ")"))
      | unique
    )
  | .permissions.allow = (
      ($b.permissions.allow // [])
      + ($allowBash | map("Bash(" + . + ")"))
      | unique
    )
  | ."$comment" = (
      ["GENERATED by avengers-12/lib/emit-settings.sh — do not edit.",
       "Write/Edit denies come from gate.deny in config.yml.",
       "Read denies come from permissions.denyRead.",
       "Bash allows come from permissions.allowBash plus the base file."]
    )
  ' > "$OUT" || die "could not build $OUT"

DENIES="$(jq '.permissions.deny | length' "$OUT")"
ALLOWS="$(jq '.permissions.allow | length' "$OUT")"
notice "settings: $OUT ($DENIES deny, $ALLOWS allow)"
set_output "settings_file" "$OUT"
